#include "Licensing/Entitlement.h"
#include "Licensing/LicenseManager.h"
#include <iostream>
using namespace hungryghost;
void require(bool result,const char* reason){if(!result)throw std::runtime_error(reason);}
int main(int argc,char** argv){juce::ScopedJuceInitialiser_GUI init;try{
 if(argc<3)throw std::runtime_error("Supply signed fixture JSON and an isolated test directory.");auto fixture=juce::JSON::parse(juce::File::getCurrentWorkingDirectory().getChildFile(argv[1]).loadFileAsString());require(fixture.isObject(),"Missing fixture JSON");auto now=static_cast<juce::int64>(fixture["now"]);auto device=fixture["device"].toString();Entitlement entitlement;
 auto verify=[&](const juce::var& value,const juce::String& d=juce::String(),const juce::String& product=juce::String("feral")){return Entitlement::verify(juce::JSON::toString(value),d.isEmpty()?device:d,product,now,entitlement).wasOk();};
 require(verify(fixture["valid"]),"Standard RSA SHA-256 signature rejected");require(entitlement.products.size()==2&&entitlement.activationId=="test-activation","Signed fields not decoded");require(!verify(fixture["expired"]),"Expired token accepted");require(!verify(fixture["future"]),"Future token accepted");require(!verify(fixture["version"]),"Unsupported version accepted");require(!verify(fixture["valid"],"b"+device.substring(1)),"Foreign device accepted");require(!verify(fixture["valid"],device,"reverb"),"Unpurchased product accepted");
 auto tampered=juce::JSON::parse(juce::JSON::toString(fixture["valid"]));auto payload=tampered["payload"].toString();tampered.getDynamicObject()->setProperty("payload",payload.substring(0,payload.length()-2)+"AA");require(!verify(tampered),"Modified payload accepted");tampered=juce::JSON::parse(juce::JSON::toString(fixture["valid"]));auto signature=tampered["signature"].toString();tampered.getDynamicObject()->setProperty("signature","AA"+signature.substring(2));require(!verify(tampered),"Modified signature accepted");require(!verify(juce::var("invalid")),"Malformed envelope accepted");
 const auto folder=juce::File::getCurrentWorkingDirectory().getChildFile(argv[2]).getChildFile("run-"+juce::Uuid().toString());folder.createDirectory();const auto realNow=juce::Time::getCurrentTime().toMilliseconds()/1000;juce::String actualDevice;{LicenseManager trial("rift",folder);require(trial.canProcess(),"New 30-day trial did not start");actualDevice=trial.device;}
 auto data=juce::var(new juce::DynamicObject());data.getDynamicObject()->setProperty("first",realNow-31*86400);data.getDynamicObject()->setProperty("last",realNow);data.getDynamicObject()->setProperty("device",actualDevice);folder.getChildFile("trial.json").replaceWithText(juce::JSON::toString(data));{LicenseManager expiredTrial("rift",folder);require(!expiredTrial.canProcess(),"Expired trial bypassed licence gate");}
 auto cached=juce::var(new juce::DynamicObject());cached.getDynamicObject()->setProperty("device",actualDevice);cached.getDynamicObject()->setProperty("allowed",true);cached.getDynamicObject()->setProperty("entitlement",juce::JSON::toString(fixture["valid"]));juce::Array<juce::var> ids;ids.add("rift");cached.getDynamicObject()->setProperty("products",ids);folder.getChildFile("entitlements").createDirectory();folder.getChildFile("entitlements/forged.json").replaceWithText(juce::JSON::toString(cached));{LicenseManager forged("rift",folder);require(!forged.canProcess(),"Unsigned cache fields authorized a processor");}
 data.getDynamicObject()->setProperty("first",realNow-86400);data.getDynamicObject()->setProperty("last",realNow+3600);folder.getChildFile("trial.json").replaceWithText(juce::JSON::toString(data));{LicenseManager rollback("rift",folder);require(!rollback.canProcess(),"Clock rollback extended the trial");}
 std::cout<<"PASS: standard RSA signature, tamper/device/product/expiry rejection, trial expiry and forged cache gates\n";return 0;
 }catch(const std::exception& e){std::cerr<<"FAIL: "<<e.what()<<'\n';return 1;}}
